# Generated by Django 4.1.7 on 2023-04-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
